### ISSUE TITLE
ofxRemoteUIClientOSX doesn't compile with 10.10 SDK

### ISSUE THREAD

**Issue by neilmendoza** [armadillu/ofxRemoteUI#16]
Works with 10.9 though.  Message is:

of_v0.8.4_osx_release/addons/ofxRemoteUI/OSX Client/src/AppDelegate.mm:18:16: Cannot initialize a variable of type 'AppDelegate *' with an rvalue of type 'id<NSFileManagerDelegate>'

**Comment by neilmendoza** [comment]
Works with 10.9 though.  Message is:

of_v0.8.4_osx_release/addons/ofxRemoteUI/OSX Client/src/AppDelegate.mm:18:16: Cannot initialize a variable of type 'AppDelegate *' with an rvalue of type 'id<NSFileManagerDelegate>'

**Comment by armadillu** [comment]
I need to add some casts, will do!

**Comment by armadillu** [comment]
Actually, I just compiled it with 10.10 sdk and it built ok... Are you on the master branch?

**Comment by neilmendoza** [comment]
Ah sorry, was on a fork.  Thanks for taking a look!
