### ISSUE TITLE
Build failed with "No matching function to object of type 'ofEvent<ofAbstractParameter>'"

### ISSUE THREAD

**Issue by harryhow** [armadillu/ofxRemoteUI#17]
Hi @armadillu 

I'm trying to use ofxRemoteUI addon with of 0.8.4, however I encounter this error msg when compile.
```
 "No matching function to object of type 'ofEvent<ofAbstractParameter>'"
````

Any hint of solving this error?
Thanks!

**Comment by armadillu** [comment]
Yeah that's bc master branch is set to compile against OF 0.9. Try removing ofxRemoteUIofParamaterSync.h and ofxRemoteUIofParamaterSync.cpp from the project... If that doesn't work, try checking out an older revision. I should make a 0.8.4 branch, or at least add a Git Tag. Will try to do that later today

**Comment by harryhow** [comment]
@armadillu just want to let you know, compile success by removing ofxRemoteUIofParamaterSync.cpp/.h. Thanks!! :+1:
