### ISSUE TITLE
Can't edit string on screen

### ISSUE THREAD

**Issue by harryhow** [armadillu/ofxRemoteUI#19]
I'm using on screen edit feature (tab) to edit string value on OF's (0.8.4) window. 

However, even I choose the right item and press 'left/right arrow key', I can not get any edit box or something to edit. (only see an animation on top of '+ PRESET SELECTION'
I can edit this string value by iOS client though. 

My code is straight forward like this, 

    RUI_NEW_GROUP("UPDATE VEGETABLE % HERE");	//make a new group (optional)
    RUI_SHARE_PARAM(currentAppleAmount, ofColor(255,0,0,64));	

Any hints?

**Comment by armadillu** [comment]
Sorry string editing is not implemented. Only ints, float, enums, bools and colors can be edited through the built in client for now. You can always use the external client.

**Comment by kritzikratzi** [comment]
maybe something like this would be good enough: 

https://github.com/armadillu/ofxRemoteUI/blob/master/src/ofxRemoteUIServer.cpp#L1115

	case REMOTEUI_PARAM_STRING: 
		p.stringVal = ofSystemTextBoxDialog("Value for ", p.stringVal ); 
		break;

**Comment by armadillu** [comment]
yeah that could work, ill add it in!

**Comment by armadillu** [comment]
Feature implemented in 23f6192f8e4fb57af9b71972be4f4e00984d8a1d.
Select a thing variable type, Press return and type in the new value the system dialog box.

**Comment by kritzikratzi** [comment]
uh, i just realize i forgot the param name, like maybe

    ofSystemTextBoxDialog("Value for " + key, p.stringVal )

not a big deal though ...

**Comment by armadillu** [comment]
yeah i fixed it in the next commit

**Comment by harryhow** [comment]
Wow @armadillu  you are awesome! I merge your change and it works on my side!! Thanks!!

I also found whenever popup edit dialogue close, the built-in client interface seems lose focus? (not responding while press any keys, I can workaround this by press cmd+tab to switch window back and forth), not sure if this only happens on my side.

**Comment by armadillu** [comment]
Yeah that window focus problem that is related to OF itself, probably the Windows implementation only... Don't see that on mac osx.
