### ISSUE TITLE
[Bug] Preset deletion doesn't work

### ISSUE THREAD

**Issue by Plastix** [armadillu/ofxRemoteUI#22]
I've noticed that deleting a preset doesn't work. I've tested with the code on `master` and the OSX client. I'm pretty sure this is a server issue because the client gets a response back from the server after sending a deletion packet but the preset XML file is never deleted.

**Comment by armadillu** [comment]
can u try on your end? should work now

**Comment by Plastix** [comment]
Yep looks like that solved it.
