### ISSUE TITLE
Collaboration ? 

### ISSUE THREAD

**Issue by jcelerier** [armadillu/ofxRemoteUI#24]
Hello ! 

I am a developer of the ossia library which has sensibly the same goals than ofxRemoteUI : https://github.com/OSSIA/API ; it also has some in-progress openframeworks, Qt, java, C, unity3D, and python bindings but the core is pure cross-platform C++.

It is used in the [i-score](https://github.com/OSSIA/i-score) sequencer to provide communication with other software. 

I woud like to know if you would be interested in collaborating so that i-score would be able to control and automate applications built with ofxRemoteUI in a time line ? The only thing to do would be to write a class in the ossia library that talks the OSC protocol of ofxRemoteUI, but I don't really know where to get started, if the protocol is fixed, etc.

**Comment by armadillu** [comment]
Hey - sorry for the super late reply!

If you are looking for a protocol spec, its outlined in here - 
https://github.com/armadillu/ofxRemoteUI/blob/master/src/ofxRemoteUI.h#L90
Should be pretty straight forward to target from another lib if you are up for it.

**Comment by jcelerier** [comment]
hello :) 

yep, that seems doable (but like everything, with enough time :p)
I'm keeping it in mind for later. thanks!
